name: Fancy2FA
version: '$version'
main: com.github.gameoholic.fancy2fa.Fancy2FA
api-version: 1.19
authors: [ Gameoholic ]
description: Test
commands:
  2fa:
    description: Sets up 2FA
    usage: /2fa